[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-unknown-linux-gnu]
rustflags = [
  "-Lnative=native/aarch64-unknown-linux-gnu",
  "-lstatic=hashtree",
  "-Ctarget-feature=-crt-static",
]
