[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

# Linux (GNU) ARM64
[target.aarch64-unknown-linux-gnu]
# make sure the submodule builds aarch64-gnu PIC objects
env.CC = "zig cc -target aarch64-linux-gnu"
env.AR = "zig ar"
env.CFLAGS = "-fPIC"

# macOS x86_64
[target.x86_64-apple-darwin]
env.CC = "zig cc -target x86_64-macos"
env.AR = "zig ar"
env.CFLAGS = "-fPIC -mmacosx-version-min=10.13"

# macOS arm64
[target.aarch64-apple-darwin]
env.CC = "zig cc -target aarch64-macos"
env.AR = "zig ar"
env.CFLAGS = "-fPIC -mmacosx-version-min=11.0"

# Linux x86_64 musl (if you build it)
[target.x86_64-unknown-linux-musl]
env.CC = "zig cc -target x86_64-linux-musl"
env.AR = "zig ar"
env.CFLAGS = "-fPIC"